<script id="paypal-js"
    src="https://www.sandbox.paypal.com/webapps/merchantboarding/js/lib/lightbox/partner.js"></script>

<a target="_blank" class="action-default" data-paypal-onboard-complete="onboardedCallback" data-paypal-button="true"
    href="<?= $block->escapeHtml($block->getRedirectUrl())?>&displayMode=minibrowser" >Sign up for PayPal</a>


<script>
    function setCookie(name, value, expirationHours) {
        const d = new Date();
        d.setTime(d.getTime() + (expirationHours*60*60*1000));
        let expires = "expires="+ d.toUTCString();
        document.cookie = name + "=" + value + ";" + expires + ";path=/";
    }

    function onboardedCallback(authCode, sharedId) {
        setCookie("authCode", authCode, 8);
        setCookie("sharedId", sharedId, 8);
    }
</script>
