<p><span><?php echo __('PayPal Express Checkout') ?></span></p>
<p><span><b><?php echo __('Transaction Id: ') ?></b><?php echo $block->getLastTransId() ?></span></p>
<p><span><b><?php echo __('Invoice Id: ') ?></b><?php echo $block->getInvoiceId() ?></span></p>
<p><span><b><?php echo __('State Payment: ') ?><?php echo $block->getStatePayPal() ?></b></span></p>
<p><a id="transaction-modal" href="#"><?php echo __('Transaction log') ?></a></p>
<p><span><b><?php echo __('Installments: ') ?></b><?php echo $block->getTerm() ?></span></p>
